### PR TITLE
Create Last Digit of the Sum of Fibonacci Numbers.py

### PR DESCRIPTION
**Pull request by TSG405**
A simple PR for a happy HACKTOBERFEST 2021!! 🥇

~ Regards
TSG405

### CODE REVIEW

**Comment by TSG405** [comment]
Can you please add the label of "hacktoberfest accepted"?

**Comment by Sangwan5688** [comment]
It's not necessary.

**Comment by Sangwan5688** [comment]
You need that label only if you are contributing to a repo which is not participating in Hacktoberfest. This repo is participating, so there's no need to add "hacktoberfest-accepted" label to each PR

**Comment by TSG405** [comment]
Yet still, if you have time .. consider myself.  :P

~ Thanks in advance
TSG405

**Comment by Sangwan5688** [comment]
I will have to add it in label first. So, it will take some time. Anyway, If your PR doesn't get accepted to Hacktoberfest, I will give you 2 T-Shirts instead. Deal??

**Comment by TSG405** [comment]
Cool XD. Btw how many days will the reviews by maintainers, get completed? It's showing 14 days to mature... So will it literally take 14 days?

Thanks

**Comment by Sangwan5688** [comment]
Yup, maintainers get a time of 14 days to accept your PRs. In that time we can either accept and merge your requests or tag them as spam or invalid. It's done that way so that maintainers can take their time to go through each one of them, coz you see we receive a lot of PRs, Like 100-200 in a day. Even if we accept them way before the 14 day period they will not mature till 14 days are complete. In those 14 days, we can tag your requests as spam if you push too many unnecessary PRs.

**Comment by TSG405** [comment]
Hey why is it showing excluded project? U said this repo is participating right?

**Pull request merged**
